# Base URL for GitHub Pages
baseURL = "https://zeusedom.github.io/workshop_aws/"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# Enable raw HTML rendering in Markdown (Goldmark parser)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = "FCAJ Internship Report & AWS Weather Dashboard Serverless Workshop by Pham The Hoai"
  author = "Pham The Hoai (phamthehoai2004hn@gmail.com)"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "FCAJ Report - AWS Weather Dashboard"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Repository"
identifier = "GitHub Repo"
url = "https://github.com/ZeusEdom/aws_final"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://aws.amazon.com/blogs"
weight = 20

[Languages.vi]
title = "Báo cáo FCAJ - AWS Weather Dashboard"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Mã nguồn GitHub"
identifier = "GitHub Repo VI"
url = "https://github.com/ZeusEdom/aws_final"
weight = 10

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "http://awsstudygroup.com"
weight = 20
